# Generated by Django 3.0.3 on 2020-02-14 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата начала')),
                ('number_players', models.IntegerField(max_length=100, verbose_name='Количество игроков')),
                ('win_score', models.SmallIntegerField(verbose_name='Количество очков для победы')),
                ('start', models.TimeField(verbose_name='Время начала')),
                ('end', models.TimeField(verbose_name='Время окончания')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('wins', models.SmallIntegerField(default=0, verbose_name='Победы игрока')),
                ('scores', models.SmallIntegerField(default=0, verbose_name='Количество очков хода')),
                ('effectivity', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Эффективность')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(default=0, verbose_name='Количество очков хода')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Players')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='winner_game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Players'),
        ),
    ]
