# Generated by Django 3.0.3 on 2020-02-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200214_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner_game',
        ),
        migrations.AddField(
            model_name='players',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
